services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
      ...
      - web15

  web1:
    image: php:8.3-apache
    volumes:
      - ./html:/var/www/html
  web2:
    image: php:8.3-apache
    volumes:
      - ./html:/var/www/html
  ...
  web15:
    image: php:8.3-apache
    volumes:
      - ./html:/var/www/html

